spring:
  profiles: development
  config:
    name: &name yakuzi-dev
  application:
    name: *name
  freemarker:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
  datasource:
    url: jdbc:log4jdbc:mysql://47.95.254.181:3306/yakuzi
    username: test-user
    password: aliyun
    driverClassName: net.sf.log4jdbc.DriverSpy

server:
  port: 80

logging:
  level:
    org:
      springframework:
        web: INFO

yakuzi:
  redis:
    host: 127.0.0.1
    port: 6379
